name: flutter_markdown
description: A Markdown renderer for Flutter. Create rich text output,
 including text styles, tables, links, and more, from plain text data
 formatted with simple Markdown tags.
homepage: https://github.com/flutter/flutter_markdown
version: 0.5.0

dependencies:
  flutter:
    sdk: flutter
  markdown: ^3.0.0
  meta: ^1.1.7
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

flutter:
  assets:
    - assets/logo.png
